beeSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
	url(r'^busybee/', include('busybee.urls')),
    url(r'^admin/', admin.site.urls),
]

busybee/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import views
from busybee.views import business,forms
from django.conf import settings
urlpatterns = [
    url(r'^$', views.busybee, name='busybee'),
    url(r'^forms/$', forms),    
    url(r'^business/$', business),
]
urlpatterns += staticfiles_urlpatterns()

busybee/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class BusyBee(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

beeSite/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message


class BusinessForm(forms.Form):
    subject = forms.CharField(max_length=10,initial="Business")
    email = forms.EmailField(required=True,initial="mail@mail.com")
    
    #Expenses
    rent = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text="Thusen SEK")
    staff_salary = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text="Thusen SEK")
    staff_count = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text= "Expected number of employees")
    electricity = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text="Thusen SEK")
    tax = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text="Tax rate")

    #Incomes
    income = forms.IntegerField(widget=forms.NumberInput,initial=10, help_text="Thusen SEK")
    
    #Details
    #ort_choices = (('1', 'Stockholm',), ('2', 'Uppsala',))
    #ort = forms.ChoiceField(widget=forms.Select, choices=ort_choices)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message		

class BusinessResultForm(forms.Form):

    #Results
    expenses = forms.IntegerField(widget=forms.NumberInput)
    income = forms.IntegerField(widget=forms.NumberInput)
    result = forms.IntegerField(widget=forms.NumberInput)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

busybee/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import Context, loader
from graphos.sources.simple import SimpleDataSource
from graphos.renderers.gchart import PieChart
from graphos.renderers.gchart import LineChart
from graphos.renderers.gchart import BarChart
# Create your views here.
from beeSite.forms import BusinessForm, BusinessResultForm
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
import json
from django.http import JsonResponse
def busybee(request):
    return HttpResponse("You're at the busybee page.")

def forms(request):
    return render(request, 'forms.html')

def business(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            result = calc_result(cd)
            _, income = result.popitem()
            _, expenses = result.popitem()
            result= income - expenses  
            beeIndex= (result/expenses)
            beeIndex = round(beeIndex, 3)
            if request.is_ajax():
                array =[
                    ['Activity', 'Parcel'],
                    ['income',   income],
                    ['expenses', expenses],
                    ['result',  result]
                    ];         

                return render(request, 'queryresponse.html', {'array':array,'beeIndex':beeIndex})
            else:
                return HttpResponse("Not complete as ajax request")               
        else:    
            return HttpResponse("Please provide valid values.")
    else:
        form = BusinessForm()
        return render(request, 'business_form.html', {'form':form})

def calc_result(cd):

    subj = cd['subject']
    email = cd.get('email', 'noreply@example.com')
    
    #Expenses
    rent = cd['rent']
    staff = cd['staff_salary']    
    staff_count = cd['staff_count']
    electricity = cd['electricity']
    tax = cd['tax']

    
    #Incomes
    sales = cd['income']
    final_tax = tax*sales/100
    #Result
    expenses = rent + staff*staff_count + electricity + final_tax
    result = {'exp':expenses, 'inc': sales}
    return result    

busybee/templates/ajax.html
<html>
  <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript">
    
    // Load the Visualization API and the piechart package.
    google.charts.load('current', {'packages':['corechart']});
      
    // Set a callback to run when the Google Visualization API is loaded.
    google.charts.setOnLoadCallback(drawChart);
      
    function drawChart() {
      var jsonData = $.ajax({
          url: "getData.php",
          dataType: "json",
          async: false
          }).responseText;
          
      // Create our data table out of JSON data loaded from server.
      var data = new google.visualization.DataTable(jsonData);

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
      chart.draw(data, {width: 400, height: 240});
    }

    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
  </body>
</html>





    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
  </head>

busybee/templates/base_form.html
<html>
<head>
	<title>Entries</title>
</head>
<body>
{{}}
</body>
</html>

busybee/templates/business_form2.html
<html>
<head>
	<title>Entries</title>
<style>
/* make sidebar nav vertical */ 
@media (min-width: 768px) {
  .sidebar-nav .navbar .navbar-collapse {
    padding: 0;
    max-height: none;
  }
  .sidebar-nav .navbar ul {
    float: none;
    display: block;
  }
  .sidebar-nav .navbar li {
    float: none;
    display: block;
  }
  .sidebar-nav .navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
  }
  form {
  width: 100%;
  border:0;
  padding:0;
  margin:0;
  }
  .field {
  width: 100%;
  border:0;
  padding:0;
  margin:0;
  }
}
</style>

  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<h2 align="center"  style="color:green" >Enter your details here</h2>
	
    {% if form.errors %}
	{{ form.errors }}
    {{ form.non_field_errors }}
    <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
 <div class="col-sm-3 col-md-3" >
 <div class="sidebar-nav">
 <div class="navbar navbar-default" role="navigation">
 <form  id="form_id" class="nav navbar-nav" action="" method="post">
  <h5>FILTER</h5>
 <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Contact</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
		      <fieldset class="field" id="general">
        <div class="field" class="panel-body">
            {{ form.email.errors }}
            <label class="label label-primary" for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
		<div class="field" class="panel-body">
            <label class="label label-primary" for="id_subject">Subject</label>
            {{ form.subject }}
        </div>      
      </fieldset>
	  </div>
	  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Input</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">
		        <div class="field">
            <label class="label label-primary" for="id_tax">Tax %</label>
            {{ form.tax }}
        </div> 
		<div class="field">
            <label class="label label-primary" for="id_rent">Rent</label>
            {{ form.rent }}
        </div>
        <div class="field">
            <label class="label label-primary" for="id_staff_salary">Staff salary:</label>
            {{ form.staff_salary }}
        </div>
        <div class="field">
            <label class="label label-primary" for="id_staffcount">Staff count:</label>
            {{ form.staff_count }}
        </div>
		<div class="field">
            <label class="label label-primary" for="id_electricity">Electricity expense:</label>
            {{ form.electricity }}
        </div>
		<div class="field">
            <label class="label label-primary" for="id_income">Income:</label>
            {{ form.income }}
        </div> 
<!--         <div class="field">
            <label for="id_ort">Ort</label>
            {{ form.ort }}
        </div>     --> 
		</div>
	    {% csrf_token %}
        <input type="submit" value="Submit">
 </div>
 </div>
  </div>
  </div>
<!--   </div> -->
<!--   </div> -->
  </form>
  </div>
  </div>
  </div>
<div class="col-sm-9 col-md-9" id="success_div"> 
<div  id="piechart"></div>
<h1>Your results</h1>
</div>
<div id="error_div"></div>

<button> Save </button>
<button onclick="getElementById('/busybee/business/')">Clear</button>


<!-- <script type="text/javascript">
$.noConflict();

$(document).ready(function() {
	$('#form_id').submit(function (event) {
	    event.preventDefault(); // Prevent the form from submitting via the browser
		var jsonData= $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
            	// Create our data table out of JSON data loaded from server.
            	var data = google.visualization.arrayToDataTable(jsonData);
            	// Instantiate and draw our chart, passing in some options.
            	var chart = new google.visualization.PieChart(document.getElementById('success_div'));
            	chart.draw(data, {width: 400, height: 240});
            },
            error: function(data) {
                $("error_div").html("Something went wrong!");
            }
        });
        return false;
    });

};

</script> -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
		
        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js"></script>

</body>
</html>

busybee/templates/business_form_last.html
<html>
<head>
	<title>Entries</title>
<style>
/* make sidebar nav vertical */ 
@media (min-width: 768px) {
  .sidebar-nav .navbar .navbar-collapse {
    padding: 0;
    max-height: none;
  }
  .sidebar-nav .navbar ul {
    float: none;
    display: block;
  }
  .sidebar-nav .navbar li {
    float: none;
    display: block;
  }
  .sidebar-nav .navbar li a {
    padding-top: 12px;
    padding-bottom: 12px;
  }
  form {
  width: 100%;
  border:0;
  padding:0;
  margin:0;
  }
  .field {
  width: 100%;
  border:0;
  padding:0;
  margin:0;
  }
}
</style>
{% load static %}
<script type="text/javascript" src="{% static 'jquery.js' %}"></script>
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
</head>
<body>
<h2 align="center"  style="color:green" >Enter your details here</h2>
	
    {% if form.errors %}
	{{ form.errors }}
    {{ form.non_field_errors }}
    <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
 <div class="col-sm-3 col-md-3" >
 <div class="sidebar-nav">
 <div class="navbar navbar-default" role="navigation">
 <form  id="form_id" class="nav navbar-nav" action="" method="post">
  <h5>FILTER</h5>
 <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Contact</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
		      <fieldset class="field" id="general">
        <div class="field" class="panel-body">
            {{ form.email.errors }}
            <label class="label label-primary" for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
		<div class="field" class="panel-body">
            <label class="label label-primary" for="id_subject">Subject</label>
            {{ form.subject }}
        </div>      
      </fieldset>
	  </div>
	  </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Input</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">
		        <div class="field">
            <label class="label label-primary" for="id_tax">Tax %</label>
            {{ form.tax }}
        </div> 
		<div class="field">
            <label class="label label-primary" for="id_rent">Rent</label>
            {{ form.rent }}
        </div>
        <div class="field">
            <label class="label label-primary" for="id_staff_salary">Staff salary:</label>
            {{ form.staff_salary }}
        </div>
        <div class="field">
            <label class="label label-primary" for="id_staffcount">Staff count:</label>
            {{ form.staff_count }}
        </div>
		<div class="field">
            <label class="label label-primary" for="id_electricity">Electricity expense:</label>
            {{ form.electricity }}
        </div>
		<div class="field">
            <label class="label label-primary" for="id_income">Income:</label>
            {{ form.income }}
        </div> 
<!--         <div class="field">
            <label for="id_ort">Ort</label>
            {{ form.ort }}
        </div>     --> 
		</div>
	    {% csrf_token %}
        <input type="submit" value="Submit">
 </div>
 </div>
  </div>
  </div>
<!--   </div> -->
<!--   </div> -->
  </form>
  </div>
  </div>
  </div>
<div class="col-sm-9 col-md-9" id="success_div"> 
<div id="error_div"></div>
<h1>Your results</h1>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load("visualization", "1", {packages:["corechart"]});
</script>
<div id="demo">
{{ chart.as_html }}
</div>
<button> Save </button>
<button onclick="getElementById('/busybee/business/')">Clear</button>
</div>

<script type="text/javascript">
var frm = $('#form_id');
$(document).ready(function() {
	frm.submit(function (event) {
	    event.preventDefault(); // Prevent the form from submitting via the browser
		$.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
               // $("#success_div").append(data);
            },
            error: function(data) {
                $("error_div").html("Something went wrong!");
            }
        });
        return false;
    });
});
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.js"></script>

</body>
</html>

busybee/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

busybee/templates/jqueryfilter.html
<!DOCTYPE html>
<html>
<head>
    <title>Sample filter</title>
    <meta name="description" content="A jquery plugin for generating a backoffice filter">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="http://momentjs.com/downloads/moment.min.js"></script>
    <script src="https://cdn.rawgit.com/dangrossman/bootstrap-daterangepicker/master/daterangepicker.js"></script>
    <script src="https://cdn.rawgit.com/ohadpartuck/jquery-filters-plugin/v0.1.1/jquery.filters.js" type="text/javascript"></script>

    <link rel="stylesheet" media="all" href="https://cdn.rawgit.com/dangrossman/bootstrap-daterangepicker/master/daterangepicker-bs3.css">
    <link rel="stylesheet" media="all" href="https://cdn.rawgit.com/ohadpartuck/jquery-filters-plugin/v0.1.1/css/jquery.filters.css">
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
  <div id="wrapper">
      <div id="filter"></div>
  </div> 

 </body>
  <script type="text/javascript">
      function sendToServer(data){
          alert('sending params to server: ' + JSON.stringify(data));
      }

      var devicesOptions = [{name: 'LGE', value: 'LGE'}, {name: 'Apple', value: 'Apple'}, {name: 'Samsung', value: 'Samsung'}],
              productOptions = [
                  {name: 'Product Name 1', value: 'product_name_1'},
                  {name: 'Product Name 2', value: 'product_name_2'},
                  {name: 'Product Name 3', value: 'product_name_3'},
                  {name: 'Product Name 4', value: 'product_name_4'},
                  {name: 'Product Name 5', value: 'product_name_5'},
                  {name: 'Product Name 6', value: 'product_name_6'},
              ],
              operatingSystemVersionOptions = [
                  {name: '8.1 (ios)', value: '8.1'},
                  {name: '8.2 (ios)', value: '8.2'},
                  {name: '5.5 (kitkat)', value: '5.5'}
              ],
              options = {
                  title: 'Simple Filter',
                  searchClickedCallback: sendToServer,
                  filterParameters: [
                      {type: 'text', attributeName: 'subject_id', name: 'Object ID', placeholder: 'placeholder text here'},
                      {type: 'date-range', attributeName: 'date_range', name: 'Date Range'},
                      {type: 'single', attributeName: 'productName',name: 'Product', options: productOptions},
                      {type: 'multi', attributeName: 'deviceName',name: 'Manufacturer', options: devicesOptions},
					  {type: 'single', attributeName: 'os', name: 'Operating System', options: operatingSystemVersionOptions},
                  ]
              };

      $('#filter').bootstrapFilter(options);

  </script>

</html>